name: Update Jio (_hdnea_) + Zee5 (hdntl) tokens in vicky.json

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u-tokens:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch remote playlists and extract tokens
      run: |
        # Fetch JioTV playlist for _hdnea_ token
        curl -sL -o jio.m3u "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jstar.m3u"
        jio_cookie=$(grep -o '_hdnea_=[^"]*' jio.m3u | head -n1)
        echo "$jio_cookie" > jio_cookie.txt

        # Fetch Zee5 playlist for hdntl token
        curl -sL -o zee.m3u "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/z5.m3u"
        zee_hdntl=$(grep -o 'hdntl=[^"]*' zee.m3u | head -n1)
        echo "$zee_hdntl" > zee_hdntl.txt

    - name: Update tokens in vicky.json
      run: |
        jio_cookie=$(cat jio_cookie.txt)
        zee_hdntl=$(cat zee_hdntl.txt)

        # Replace Jio (_hdnea_) in both Cookie headers and stream URLs
        sed -i "s#_hdnea_=[^& ]*#${jio_cookie}#g" vicky.json
        sed -i "s#cookie=_hdnea_=[^& ]*#cookie=${jio_cookie}#g" vicky.json

        # Replace Zee5 (hdntl) in both Cookie headers and stream URLs
        sed -i "s#hdntl=[^& ]*#${zee_hdntl}#g" vicky.json
        sed -i "s#cookie=hdntl=[^& ]*#cookie=${zee_hdntl}#g" vicky.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add vicky.json
        git commit -m "Auto-update _hdnea_ and hdntl tokens in vicky.json" || echo "No changes"
        git push
